### ISSUE TITLE
Size of the chessboard?

### ISSUE THREAD

**Issue by ldh243** [vitogit/vue-chessboard#6]
Hi guy, thank you for this chess board.

I have a problem. How can I change width and height of the chess board.

I tried to change by css but it didn't work because distance of the chess is fixed 40px.

Sorry for my worst english

**Comment by ldh243** [comment]
Thank you. I find out the way to change size. We just set font size for coord tag. :D

**Comment by jersobh** [comment]
how did you changed the size?

**Comment by ldh243** [comment]
> how did you changed the size?

I just override css width & height of the chessboard. 

Remember to refresh page. Library will load position of any chessman, length of step,...

I didnt load page so I had this problem.

**Comment by Matthew-Nicholson** [comment]
I'm having this problem as well. How exactly do you change the size of the board from it's default 320 pixels? It's not responding to CSS and I'm not seeing any available props.

Edit: Actually, this is probably a problem on my end. I think scoped CSS breaks this component.
