### ISSUE TITLE
is it possible to load / explore game from pgn file?

### ISSUE THREAD

**Issue by vesper8** [vitogit/vue-chessboard#8]
Just wondering if it's currently possible or if you plan on adding this feature?

Thanks!

**Comment by vitogit** [comment]
Hi @vesper8 currently this project is just to show positions, but you can build a pgn viewer using this library together with some other like chess.js to load the pgn and validate moves. 
I did something similar in other projects like
http://tacticalchess.vitomd.com/
http://vitomd.com/vue-chess-guardian/

Anyway a pgn viewer sounds like a fun project. If you do it, let me know.
