### ISSUE TITLE
Missed move in history in case of a checkmate

### ISSUE THREAD

**Issue by PureLines** [vitogit/vue-chessboard#9]
You can see this behaviour at http://vitomd.com/vue-chessboard-examples/.

When a move results in a checkmate, the last move doesn't appear in history.

Also an error appears in console in this case:
```
vue-chessboard.common.js:1:73024
TypeError: e is null
    afterMove vue-chessboard.common.js:1
    afterMove self-hosted:844
    changeTurn vue-chessboard.common.js:1
    r vue-chessboard.common.js:1
```

**Comment by vitogit** [comment]
Thanks for the report, I will take a look

**Comment by PureLines** [comment]
Seems, you didn't publish latest version to npm. 
This code is from npm 0.6.5:
```js
    afterMove () {
      if (this.showThreats) {
        this.paintThreats()
      }
      let threats = this.countThreats(this.toColor())  // this line
      threats['history'] = this.game.history()
      threats['fen'] = this.game.fen()
      this.$emit('onMove', threats)
    },
```

And this is in master branch:
https://github.com/vitogit/vue-chessboard/blob/fe6a5e2d08198db6acfed2256a54ff28e440c2c2/src/components/chessboard/index.vue#L125-L133

**Comment by vitogit** [comment]
@PureLines Yes you are right, I never pushed the changes to npm. It should be working now, also I updated http://vitomd.com/vue-chessboard-examples/ with the latest version (0.6.6).  Let me know if you have any issues

**Comment by PureLines** [comment]
Great! Now it works well. 
Thank you!

**Comment by vitogit** [comment]
Thank you for reporting the issue.
